//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.07.11 at 01:08:49 PM EDT 
//


package com.nonder;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for bodyStyle.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="bodyStyle">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="HATCHBACK"/>
 *     &lt;enumeration value="SEDAN"/>
 *     &lt;enumeration value="SUV"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "bodyStyle")
@XmlEnum
public enum BodyStyle {

    HATCHBACK,
    SEDAN,
    SUV;

    public String value() {
        return name();
    }

    public static BodyStyle fromValue(String v) {
        return valueOf(v);
    }

}
